name: aeye
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  http: ^1.1.2
  flutter_markdown: ^0.6.18
  image_picker: ^1.0.7
  flutter_blue_plus: ^1.31.16
  permission_handler: ^11.3.0
  dio: ^5.4.1
  frame_sdk: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
